### ISSUE TITLE
New Page Total doesn't update current page

### ISSUE THREAD

**Issue by MarcGodard** [icanjs/grid-component#15]
When you run a filter and get a new page total, you do not reset the page number.

So if you are on page 2, and filter and change the pagination total lower, it displays blank, not page 1.

Is there a way to reset this? I have tried to use the changePage function as a callback on my filter functions, which works, however it doesn't reset it internally so it displays the first page, but not update the isActive or the pageNumber / pageTitle variables.

I started working on this, but I can't seem to figure it out.

**Comment by green3g** [comment]
What have you tried? I usually would do something like this:
```javascript
    filters: {
        set(filters){
            this.currentPage = 1;
            return filters;
        }
    }
```

**Comment by MarcGodard** [comment]
The problem is the filters are set outside the component. And the component doesn't seem to update on variable changes.

**Comment by chasenlehara** [comment]
Assuming that `mixings/pagination.js` is the right place to look for the issue, is [changePage](https://github.com/icanjs/grid-component/blob/8b3bbe5caadf391041174b0fd9b5c16105bd3844/src/mixins/pagination.js#L136) being called with an invalid `pageNumber`? Or is `currentPage` wrong inside the [pages getter](https://github.com/icanjs/grid-component/blob/8b3bbe5caadf391041174b0fd9b5c16105bd3844/src/mixins/pagination.js#L102)?

When you say “filters are set outside the component,” does that mean something outside the component is changing the `rows` passed in, and the internal state of grid-component isn’t updating to reflect that? Sorry I am not familiar with the grid-component code, just trying to throw out some ideas of where to look.

**Comment by MarcGodard** [comment]
@chasenlehara Yes, outside the component the rows are being updated with a filter. However, when it does this, it also updates the pagination variable that is bind: with the component updating pagination.total. This should update the component but doesn't. I am not sure why.

**Comment by MarcGodard** [comment]
I figured a way around this issue.
