### ISSUE TITLE
changePage function doesn't get called.

### ISSUE THREAD

**Issue by MarcGodard** [icanjs/grid-component#18]
In the newest version for canjs4 `prev()` and `next()` get called, but not `changePage()`.

```
WARN: can-stache/expressions/lookup.js: Unable to find key "@changePage".
```

**Comment by ilyavf** [comment]
Fixed examples and readme. Basically, the function call is inside `{{#each...}}`, so exact scope needs to be defined:
```
{{#each(pages)}}
    <... on:click="../changePage(pageNumber)" />
{{/each}}
```
