### ISSUE TITLE
Not able run any of the demo html 

### ISSUE THREAD

**Issue by santoshgiridhar** [icanjs/grid-component#3]
Under, grid component demo folder not able to run the demo files.
Keep getting steal.js path error. Even after manually adding path or changing the absolute path.

/node_modules/grid-component/steal/steal.js 404 (Not Found)

**Comment by ilyavf** [comment]
Hi @santoshgiridhar, if you clone grid-component project and run locally the demo, its working:

![image](https://cloud.githubusercontent.com/assets/1895948/15757183/617958e4-28d2-11e6-8c49-02ad1dbd1905.png)

But it would be good to have a live demo, so we will create a gh-page for this.

Regarding to the error you posted, could you point me to your project and your demo file? I will be able to help.

**Comment by marshallswain** [comment]
Did you `npm install`, first?

**Comment by ilyavf** [comment]
Oh, I think @santoshgiridhar tried to run the demo from inside `node_modules/grid_component` folder. If I try this I get the same error as he.

So, what u can do is: run `npm install` inside your `node_modules/grid_component`; then run `http-server` again inside, and then run the demo as: `http://localhost:8080/src/demo/demo.html`
This will work for (I just checked).
